## Numpy Wine Quality 데이터 실습

### 와인 품질 데이터 셋

**컬럼의 종류**

- **fixed.acidity(결합산)** : 와인의 산도를 제어한다.
- **volatile.acidity(휘발산)** : 와인의 향에 연관이 많다.
- **citric.acid(구연산)** : 와인의 신선함을 유지시켜주는 역할을 하며, 산성화에 연관을 미친다.
- **residual.sugar(잔여 설탕)** : 와인의 단맛을 올려준다.
- **chlorides(염소)** : 와인의 짠맛과 신맛을 좌우하는 성분이다.
- **free.sulfur.dioxide / total.sulfur.dioxide / sulphates(황 화합물)** : 특정 박테리아와 효모를 죽여 와인의 보관도를 높여준다.
- **density(밀도)** : 바디의 높고 낮음을 표현하는 와인의 바디감을 의미한다.
- **pH(산성도)** : 와인의 신맛의 정도를 나타낸다.
- **alcohol(알코올)** : 와인에 단맛을 주며 바디감에 영향을 준다.
- ***quality(퀄리티)*** : 결과적으로 다른 변수들을 이용하여 예측하려고 하는 변수로 와인의 퀄리티를 나타낸다.

In [1]:
import pandas as pd

In [5]:
df = pd.read_csv('data/winequality-red.csv', sep=';')

In [6]:
df.head()

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0            7.4              0.70         0.00             1.9      0.076   
1            7.8              0.88         0.00             2.6      0.098   
2            7.8              0.76         0.04             2.3      0.092   
3           11.2              0.28         0.56             1.9      0.075   
4            7.4              0.70         0.00             1.9      0.076   

   free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
0                 11.0                  34.0   0.9978  3.51       0.56   
1                 25.0                  67.0   0.9968  3.20       0.68   
2                 15.0                  54.0   0.9970  3.26       0.65   
3                 17.0                  60.0   0.9980  3.16       0.58   
4                 11.0                  34.0   0.9978  3.51       0.56   

   alcohol  quality  
0      9.4        5  
1      9.8        5  
2      9.8        5  
3      9.8        6  
4      9.4        5

In [7]:
df.describe()

fixed acidity  volatile acidity  citric acid  residual sugar  \
count    1599.000000       1599.000000  1599.000000     1599.000000   
mean        8.319637          0.527821     0.270976        2.538806   
std         1.741096          0.179060     0.194801        1.409928   
min         4.600000          0.120000     0.000000        0.900000   
25%         7.100000          0.390000     0.090000        1.900000   
50%         7.900000          0.520000     0.260000        2.200000   
75%         9.200000          0.640000     0.420000        2.600000   
max        15.900000          1.580000     1.000000       15.500000   

         chlorides  free sulfur dioxide  total sulfur dioxide      density  \
count  1599.000000          1599.000000           1599.000000  1599.000000   
mean      0.087467            15.874922             46.467792     0.996747   
std       0.047065            10.460157             32.895324     0.001887   
min       0.012000             1.000000              6.000000     0.990070   
25%       0.070000             7.000000             22.000000     0.995600   
50%       0.079000            14.000000             38.000000     0.996750   
75%       0.090000            21.000000             62.000000     0.997835   
max       0.611000            72.000000            289.000000     1.003690   

                pH    sulphates      alcohol      quality  
count  1599.000000  1599.000000  1599.000000  1599.000000  
mean      3.311113     0.658149    10.422983     5.636023  
std       0.154386     0.169507     1.065668     0.807569  
min       2.740000     0.330000     8.400000     3.000000  
25%       3.210000     0.550000     9.500000     5.000000  
50%       3.310000     0.620000    10.200000     6.000000  
75%       3.400000     0.730000    11.100000     6.000000  
max       4.010000     2.000000    14.900000     8.000000

### 리스트로 데이터 불러오기


In [36]:
import csv 
with open('data/winequality-red.csv', 'r') as f:
    wines = list(csv.reader(f, delimiter=';'))

In [9]:
len(wines)

1600

In [12]:
wines[0]

['fixed acidity',
 'volatile acidity',
 'citric acid',
 'residual sugar',
 'chlorides',
 'free sulfur dioxide',
 'total sulfur dioxide',
 'density',
 'pH',
 'sulphates',
 'alcohol',
 'quality']

In [13]:
wines[0][0] # 2차원 리스트임을 알 수 있다.

'fixed acidity'

In [28]:
# 문제: quality 컬럼의 값들의 평균
quality_lst = []
for i in range(1, len(wines)):
    quality_lst.append(float(wines[i][-1]))

# len(quality_lst) : 1599개 확인

sum(quality_lst) / len(quality_lst)

5.6360225140712945

- Numpy

In [29]:
import numpy as np

In [176]:
# 리스트 -> numpy의 array 객체(배열)
colunms = wines[0]
wines = np.array(wines[1:], dtype=np.float)

C:\Users\Playdata\AppData\Local\Temp\ipykernel_3312\3664471126.py:3: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  wines = np.array(wines[1:], dtype=np.float)


In [38]:
wines.shape # 1599행의 12열

(1599, 12)

In [39]:
colunms

['fixed acidity',
 'volatile acidity',
 'citric acid',
 'residual sugar',
 'chlorides',
 'free sulfur dioxide',
 'total sulfur dioxide',
 'density',
 'pH',
 'sulphates',
 'alcohol',
 'quality']

In [45]:
# 0으로 채워진 array 생성
np.zeros((3,4)) #2차원배열

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [41]:
np.zeros(3) # 1차원 배열

array([0., 0., 0.])

In [46]:
# random 값으로 array 생성
np.random.rand(3,4) # 3행 4열인 배열 랜덤 생성, 2차원 배열(행렬)

array([[0.12815924, 0.43274942, 0.36607711, 0.43522921],
       [0.15789181, 0.81183928, 0.6254535 , 0.68530002],
       [0.6732555 , 0.42149301, 0.79386301, 0.31573714]])

In [47]:
np.random.rand(3) # 1차원(벡터)

array([0.65162196, 0.72656704, 0.22309167])

In [50]:
np.random.rand(2,3,3) # 3차원

array([[[0.14688047, 0.84900053, 0.17236748],
        [0.00448237, 0.82413988, 0.08443871],
        [0.02817402, 0.60961884, 0.69464096]],

       [[0.12007561, 0.7118487 , 0.37995293],
        [0.60304244, 0.04897222, 0.53639254],
        [0.4140335 , 0.58386798, 0.47080253]]])

In [51]:
# 파일 -> numpy array로 데이터 생성
wines = np.genfromtxt('data/winequality-red.csv', delimiter=';', skip_header=1)
len(wines)

1599

In [52]:
wines.dtype

dtype('float64')

In [54]:
wines.shape

(1599, 12)

In [73]:
wines.ndim # 2차원 배열임을 알 수 있다

2

In [56]:
# 1 번째 와인의 Quality는?
wines[0,11] # 첫 번째 행의 11번째 컬럼 = wines[0,-1]

5.0

- 슬라이싱

In [59]:
# 앞에서 3개 와인의 평점
wines[:3,-1]

array([5., 5., 5.])

In [61]:
# 10 번째 와인의 모든 특성(컬럼)을 선택
wines[9,:] # = wines[9]

array([7.500e+00, 5.000e-01, 3.600e-01, 6.100e+00, 7.100e-02, 1.700e+01,
       1.020e+02, 9.978e-01, 3.350e+00, 8.000e-01, 1.050e+01, 5.000e+00])

In [66]:
# 11 번째 와인의 ['fixed acidity', 'volatile acidity', 'citric acid']의 특성만 선택
wines[10,:3]

array([6.7 , 0.58, 0.08])

In [74]:
# 11-20 번째 와인의 ['alcohol', 'quality']의 특성만 선택
wines[10:20, -2:]

array([[ 9.2,  5. ],
       [10.5,  5. ],
       [ 9.9,  5. ],
       [ 9.1,  5. ],
       [ 9.2,  5. ],
       [ 9.2,  5. ],
       [10.5,  7. ],
       [ 9.3,  5. ],
       [ 9. ,  4. ],
       [ 9.2,  6. ]])

In [76]:
wines[:,:].shape

(1599, 12)

- 3차원 배열

In [77]:
arr_1d = np.array([500, 505, 490, 810, 450, 678, 234, 897, 430, 560, 1023, 640])

In [78]:
arr_1d.shape

(12,)

In [79]:
# 분기별, 월별 판매 개수
arr_2d = np.array([
    [500, 505, 490],
    [810, 450, 678],
    [234, 897, 430],
    [560, 1023, 640],
])
arr_2d.shape

(4, 3)

In [81]:
# 1분기 판매 개수의 총합
sum(arr_2d[0]) #[0,:]

1495

In [85]:
# 분기별 첫 번째 달(1, 4, 7, 10)
sum(arr_2d[:,0])

2104

In [89]:
# 상반기 판매개수 총합(1-2분기)
sum(sum(arr_2d[:2])) 

3433

In [91]:
# 1년 전체 판매 총합
sum(sum(arr_2d))

7217

In [109]:
# 1, 3 분기 판매 총합
sum(sum(arr_2d[::2,:]))   

3056

In [113]:
arr_2d[[0,2],:]

array([[500, 505, 490],
       [234, 897, 430]])

In [98]:
# 2분기 3번째(6) ~ 3분기 1~2(8)번째 판매총합
arr_2d[1,2] + sum(arr_2d[2,:2])

1809

In [107]:
sum(np.concatenate(arr_2d)[5:8])

1809

In [115]:
# 1-3 분기 각 두번째 달(2,5,8월) 판매 총합
sum(arr_2d[:3,1])

1852

In [117]:
# 3차원
arr_2d_next = arr_2d * 1.2
arr_2d_next

array([[ 600. ,  606. ,  588. ],
       [ 972. ,  540. ,  813.6],
       [ 280.8, 1076.4,  516. ],
       [ 672. , 1227.6,  768. ]])

In [118]:
arr_2d_next.shape

(4, 3)

In [121]:
# 4행 3열의 테이블을 2개 가지고 있는 배열이다.
arr_3d = np.array([arr_2d, arr_2d_next])
arr_3d.shape

(2, 4, 3)

In [124]:
arr_3d

array([[[ 500. ,  505. ,  490. ],
        [ 810. ,  450. ,  678. ],
        [ 234. ,  897. ,  430. ],
        [ 560. , 1023. ,  640. ]],

       [[ 600. ,  606. ,  588. ],
        [ 972. ,  540. ,  813.6],
        [ 280.8, 1076.4,  516. ],
        [ 672. , 1227.6,  768. ]]])

In [122]:
# 2개의 년도에 대해서 12개의 매출데이터를 가지고 있다
# 2번째 연도의 판매 데이터
arr_3d[1,:,:]

array([[ 600. ,  606. ,  588. ],
       [ 972. ,  540. ,  813.6],
       [ 280.8, 1076.4,  516. ],
       [ 672. , 1227.6,  768. ]])

In [123]:
# 1, 2번째 연도의 1분기
arr_3d[:2,0,:]

array([[500., 505., 490.],
       [600., 606., 588.]])

In [125]:
# 각 년도의 1월
arr_3d[:, 0, 0]

array([500., 600.])

In [127]:
# 각 년도의 2, 3분기 데이터
arr_3d[:,1:3,:]

array([[[ 810. ,  450. ,  678. ],
        [ 234. ,  897. ,  430. ]],

       [[ 972. ,  540. ,  813.6],
        [ 280.8, 1076.4,  516. ]]])

In [128]:
# 각 년도의 1, 3분기 데이터
arr_3d[:,::2,:]

array([[[ 500. ,  505. ,  490. ],
        [ 234. ,  897. ,  430. ]],

       [[ 600. ,  606. ,  588. ],
        [ 280.8, 1076.4,  516. ]]])

In [133]:
arr_3d[:,[0,2],:]

array([[[ 500. ,  505. ,  490. ],
        [ 234. ,  897. ,  430. ]],

       [[ 600. ,  606. ,  588. ],
        [ 280.8, 1076.4,  516. ]]])

In [136]:
# 각 연도의 2,3분기 데이터
arr_3d[:, 1:3 ,:]

array([[[ 810. ,  450. ,  678. ],
        [ 234. ,  897. ,  430. ]],

       [[ 972. ,  540. ,  813.6],
        [ 280.8, 1076.4,  516. ]]])

- 넘파이 연산

In [137]:
# 리스트 연산
[1, 2, 3] + [1, 2, 3]

[1, 2, 3, 1, 2, 3]

In [142]:
[1, 2, 3] * 3

[1, 2, 3, 1, 2, 3, 1, 2, 3]

In [138]:
# 배열: 요소별 계산
np.array([1, 2, 3]) + np.array([1, 2, 3])

array([2, 4, 6])

In [140]:
# 브로드 캐스팅 -> np.array([10,10,10])
np.array([1, 2, 3]) + 10

array([11, 12, 13])

In [141]:
np.array([1, 2, 3]) * 3

array([3, 6, 9])

In [143]:
np.array([1, 2, 3]) * np.array([1, 2, 3])

array([1, 4, 9])

In [144]:
np.array([1, 2, 3]) - np.array([1, 2, 3])

array([0, 0, 0])

In [145]:
np.array([[1, 2, 3], [4, 5, 6]]) * np.array([1, 2, 3]) 

array([[ 1,  4,  9],
       [ 4, 10, 18]])

In [147]:
# 위와 동일함을 알 수 있다.
np.array([[1, 2, 3], [4, 5, 6]]) * np.array([[1, 2, 3], [1, 2, 3]]) 

array([[ 1,  4,  9],
       [ 4, 10, 18]])

- 넘파이 함수

In [152]:
# 내장함수
sum(wines[:,11]) # quality

9012.0

In [153]:
# 넘파이 함수(method)
wines[:,11].sum()

9012.0

In [154]:
wines[:,:11].mean()

8.134219224515324

In [155]:
# axis (축)
arr_2d = np.array([[1,2,3,4,5], [1,2,3,4,5]])
arr_2d.shape

(2, 5)

In [156]:
arr_2d.sum(axis=0) # 열 기준

array([ 2,  4,  6,  8, 10])

In [157]:
arr_2d.sum(axis=1) # 행 기준

array([15, 15])

In [158]:
arr_2d.sum() # 전체를 더함

30

In [160]:
wines.mean(axis=0) # 컬럼 마다의 평균

array([ 8.31963727,  0.52782051,  0.27097561,  2.5388055 ,  0.08746654,
       15.87492183, 46.46779237,  0.99674668,  3.3111132 ,  0.65814884,
       10.42298311,  5.63602251])

In [159]:
wines.mean(axis=1) # 행의 개수 만큼 더함

array([ 6.21198333, 10.25456667,  8.30825   , ...,  8.37347833,
        8.76795583,  7.7077075 ])

- 비교

In [162]:
# 리스트에는 비교 연산자를 사용할 수 없다.
[-2, -1, 0, 1, 2] > 0

TypeError: '>' not supported between instances of 'list' and 'int'

In [163]:
# 넘파이 array 에서는 각각 비교를 해준다.
np.array([-2, -1, 0, 1, 2]) > 0

array([False, False, False,  True,  True])

In [166]:
np.array([-2, -1, 0, 1, 2]) > 0 # 0이 브로드 캐스팅되서 0,0,0,0,0 이 된다.

array([False, False, False,  True,  True])

In [167]:
np.array([-2, -1, 0, 1, 2]) > np.array([-2, -1, 0, 0, 0])

array([False, False, False,  True,  True])

In [169]:
np.array([-2, -1, 0, 1, 2]) == 0

array([False, False,  True, False, False])

- Subsetting

In [170]:
np.array([1,2,3,4,5])[[True,False,True,True,True]]

array([1, 3, 4, 5])

In [171]:
np.array([1,2,3,4,5])[np.array([1,2,3,4,5])%2==1] #불링값이 대괄호에 들어가면 필터링이된다. 

array([1, 3, 5])

In [187]:
# wines 객체에서 알콜, 퀄리티 컬럼만 추출하고, 그 중에서 퀄리티가 8인 와인 추출
wines[:,-2:][wines[:,-1]==8] 

array([[12.8,  8. ],
       [12.6,  8. ],
       [12.9,  8. ],
       [ 9.8,  8. ],
       [13.4,  8. ],
       [11.7,  8. ],
       [11. ,  8. ],
       [11. ,  8. ],
       [14. ,  8. ],
       [12.7,  8. ],
       [12.5,  8. ],
       [11.8,  8. ],
       [13.1,  8. ],
       [11.7,  8. ],
       [14. ,  8. ],
       [10. ,  8. ],
       [11.3,  8. ],
       [11.4,  8. ]])

In [192]:
# wines 객체에서 알콜, 퀄리티 컬럼만 추출하고, 그 중에서 퀄리티가 8이면서 알콜이 13도 이상 와인 추출
# 넘파이는 요소별 연산을 하기 때문에 논리연산자 and, or 연산이 아닌 비트연산자 &, | 을 사용해야한다.
wines[:,-2:][(wines[:,-1]==8) & (wines[:,-2]>13)]

array([[13.4,  8. ],
       [14. ,  8. ],
       [13.1,  8. ],
       [14. ,  8. ]])

In [194]:
wines[wines[:,-1]==8, -2:] # 더 간결

array([[12.8,  8. ],
       [12.6,  8. ],
       [12.9,  8. ],
       [ 9.8,  8. ],
       [13.4,  8. ],
       [11.7,  8. ],
       [11. ,  8. ],
       [11. ,  8. ],
       [14. ,  8. ],
       [12.7,  8. ],
       [12.5,  8. ],
       [11.8,  8. ],
       [13.1,  8. ],
       [11.7,  8. ],
       [14. ,  8. ],
       [10. ,  8. ],
       [11.3,  8. ],
       [11.4,  8. ]])

In [195]:
wines[:,-2:][wines[:,-1]==8] # 일단 해당 두 열만 추출 -> 해당 행만 추출

array([[12.8,  8. ],
       [12.6,  8. ],
       [12.9,  8. ],
       [ 9.8,  8. ],
       [13.4,  8. ],
       [11.7,  8. ],
       [11. ,  8. ],
       [11. ,  8. ],
       [14. ,  8. ],
       [12.7,  8. ],
       [12.5,  8. ],
       [11.8,  8. ],
       [13.1,  8. ],
       [11.7,  8. ],
       [14. ,  8. ],
       [10. ,  8. ],
       [11.3,  8. ],
       [11.4,  8. ]])

In [196]:
wines[:,-2:][wines[:,-1]==8][wines[:,-2:][wines[:,-1]==8][:,-2]>13]

array([[13.4,  8. ],
       [14. ,  8. ],
       [13.1,  8. ],
       [14. ,  8. ]])

In [201]:
condition_quality = (wines[:,-1]==8)
#condition_quality[:10]
wines[:,-2:][condition_quality]

array([[12.8,  8. ],
       [12.6,  8. ],
       [12.9,  8. ],
       [ 9.8,  8. ],
       [13.4,  8. ],
       [11.7,  8. ],
       [11. ,  8. ],
       [11. ,  8. ],
       [14. ,  8. ],
       [12.7,  8. ],
       [12.5,  8. ],
       [11.8,  8. ],
       [13.1,  8. ],
       [11.7,  8. ],
       [14. ,  8. ],
       [10. ,  8. ],
       [11.3,  8. ],
       [11.4,  8. ]])

In [205]:
wines[condition_quality, -2:]

array([[12.8,  8. ],
       [12.6,  8. ],
       [12.9,  8. ],
       [ 9.8,  8. ],
       [13.4,  8. ],
       [11.7,  8. ],
       [11. ,  8. ],
       [11. ,  8. ],
       [14. ,  8. ],
       [12.7,  8. ],
       [12.5,  8. ],
       [11.8,  8. ],
       [13.1,  8. ],
       [11.7,  8. ],
       [14. ,  8. ],
       [10. ,  8. ],
       [11.3,  8. ],
       [11.4,  8. ]])

- combine

In [229]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])

result = np.vstack([arr1,arr2]) # 세로로 쌓는다
result

array([[1, 2, 3],
       [4, 5, 6]])

In [208]:
result.shape

(2, 3)

In [211]:
result2 = np.vstack([result,result])
result2

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [213]:
result2.shape

(4, 3)

In [215]:
# 가로쌓기 hstack
np.hstack([result,result])

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [216]:
np.concatenate([result,result], axis=1) #행(가로)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [217]:
np.concatenate([result,result], axis=0) #열(세로)

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [218]:
# Task_1: 레드와인, 화이트와인을 결합해라 (red wine, white wine)


In [219]:
# import csv 
# with open('data/winequality-white.csv', 'r') as f:
#     white_wines = list(csv.reader(f, delimiter=';'))

# with open('data/winequality-red.csv', 'r') as f:
#     red_wines = list(csv.reader(f, delimiter=';'))

In [2]:
import numpy as np
red_wines = np.genfromtxt('data/winequality-red.csv', delimiter= ';', skip_header = 1)
white_wines = np.genfromtxt('data/winequality-white.csv', delimiter= ';', skip_header = 1)

In [3]:
all_wines = np.concatenate([red_wines,white_wines], axis=0) #열(세로)

In [4]:
all_wines.shape

(6497, 12)

In [5]:
# color 컬럼을 추가하여 레드와인이면 1을 화이트와인이면 0을 넣는다
red_wines_cnt = red_wines.shape[0]
white_wines_cnt = white_wines.shape[0]

In [6]:
red_wines_color = [[1]] * red_wines_cnt 

In [7]:
white_wines_color = [[0]] * white_wines_cnt

In [8]:
color = np.concatenate([red_wines_color,white_wines_color], axis=0) #열(세로)

In [9]:
color.shape

(6497, 1)

In [10]:
color

array([[1],
       [1],
       [1],
       ...,
       [0],
       [0],
       [0]])

In [11]:
all_wines = np.hstack([all_wines,color])

In [12]:
all_wines.shape

(6497, 13)

In [13]:
tmp = np.array([[1,1,1]])
tmp.transpose()

array([[1],
       [1],
       [1]])

In [14]:
tmp = [i for i in range(100)]
import random
random.shuffle(tmp)
tmp[:20]

[92, 61, 86, 16, 65, 41, 56, 27, 54, 32, 93, 88, 98, 22, 4, 76, 14, 89, 96, 36]

In [15]:
# training set 80: test set 20
# 랜덤 셔플 
import random
all_wines_cnt = all_wines.shape[0] # == len(all_wines)
train_cnt = int(all_wines_cnt*0.8)
idx = [i for i in range(all_wines_cnt)]
random.shuffle(idx)
train_idx, test_idx = idx[:train_cnt], idx[train_cnt:]

In [16]:
len(train_idx)

5197

In [17]:
len(test_idx)

1300

In [18]:
train_set = all_wines[train_idx,:]
test_set = all_wines[test_idx,:]

In [19]:
train_set.shape

(5197, 13)

In [20]:
test_set.shape

(1300, 13)

In [21]:
test_set

array([[ 7.  ,  0.6 ,  0.12, ..., 10.2 ,  7.  ,  1.  ],
       [ 7.2 ,  0.15,  0.39, ..., 10.  ,  5.  ,  0.  ],
       [ 8.1 ,  0.66,  0.7 , ...,  9.  ,  5.  ,  1.  ],
       ...,
       [ 7.8 ,  0.56,  0.19, ...,  9.5 ,  5.  ,  1.  ],
       [10.4 ,  0.44,  0.42, ...,  9.9 ,  3.  ,  1.  ],
       [ 6.9 ,  0.21,  0.62, ..., 10.2 ,  6.  ,  0.  ]])

In [354]:
# 다른 방법(미루님)
# np.random.shuffle(all_wines)
# train_cnt = int(len(all_wines)*0.8)
# test_set = all_wines[:train_cnt, :]
# traing_set = all_wines[train_cnt:, :]

In [ ]:
# 다른 방법(성재님)
# np.random.shuffle(all_wines_test)
# train_set = all_wines_test[:int(len(all_wines_test)*0.8)]
# test_set = all_wines_test[int(len(all_wines_test)*0.8):]

In [24]:
# 이 데이터 셋들이 비율이 맞는지 (0,1로만 이루어진 컬럼이기 때문에 평균을 구해서 비교해볼수있다)
train_set[:,-1].mean()

0.24475659034058111

In [25]:
test_set[:,-1].mean()

0.25153846153846154